### ISSUE TITLE
How can I run this project by `npm run start` or something?

### ISSUE THREAD

**Issue by doYouHearPeopleSing** [RuurdBijlsma/Ruurd-Movie-Maker#9]
thanks a lot !

I am a learner in Electron , I  git clone this project ,but I can't run this program ,how can I run it ?

**Comment by RuurdBijlsma** [comment]
Run `electron .` at the main directory with electron in the path. 

This is an older project of mine where I was still learning electron myself, I have better usage of electron at https://github.com/RuurdBijlsma/VueMusic although this integrates with Vue which might add unnecessary confusion
